### ISSUE TITLE
Underlying stream is not writable after reconnect

### ISSUE THREAD

**Issue by cursedcoder** [thruway/pawl-transport#1]
So `WebSocket` is closed and no longer possible to write https://github.com/ratchetphp/Pawl/blob/master/src/WebSocket.php#L139

and hereby pawl provider doesn't recreate new websocket upon reconnect

you can read suggestion of cboden here https://github.com/ratchetphp/Pawl/issues/39#issuecomment-269913378

**Comment by mbonneau** [comment]
Can you please give an example of the code and how to reproduce the problem that you are having. We use this in many clients and have no problems with reconnects.

**Comment by cursedcoder** [comment]
@mbonneau false alert, closing.
